/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author student
 */
public class NimJFrame extends javax.swing.JFrame {

    private int gameState;
    private int whoseTurn;
    /**
     * Creates new form NimJFrame
     */
    public NimJFrame() {
        initComponents();
        
        this.newGame();
    }

    public void newGame() {
        this.gameState = Constants.IN_PLAY;
        this.lblScore.setText(""+Constants.INITIAL_PILE_SIZE);
        this.lblTurn.setText("Player 1's turn");
        this.whoseTurn = Constants.P1TURN;
    }
    
    private void checkForWinner() {
        int winner = -1;
        if (Integer.parseInt(lblScore.getText()) == 0) {
            winner = whoseTurn;
        }
        if (winner != -1) {
            lblTurn.setText("Player "+winner+" wins!");
            this.gameState = winner;
        }
    }
    
    private void updateTurn() {
        this.whoseTurn = (this.whoseTurn == Constants.P1TURN ? Constants.P2TURN : Constants.P1TURN);
        lblTurn.setText("Player "+this.whoseTurn+"'s turn");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTurn = new javax.swing.JLabel();
        lblScore = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTurn.setText("Player \"\" turn");

        lblScore.setText("jLabel1");

        jButton1.setText("1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClicked(evt);
            }
        });

        jButton2.setText("2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClicked(evt);
            }
        });

        jButton3.setText("3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jButton1)
                .addGap(108, 108, 108)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(28, 28, 28))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblTurn)
                        .addGap(150, 150, 150))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblScore)
                        .addGap(171, 171, 171))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblTurn)
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(47, 47, 47)
                .addComponent(lblScore, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClicked(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClicked
        // TODO add your handling code here:
        javax.swing.JButton btn = (javax.swing.JButton) evt.getSource();
        int btnVal = Integer.parseInt(btn.getText());
        int curScore = Integer.parseInt(lblScore.getText());
        if (curScore >= btnVal) {
            int newScore = curScore - btnVal;
            lblScore.setText(""+newScore);
            this.checkForWinner();
            if (this.gameState == Constants.IN_PLAY) {
                this.updateTurn();
            }
        }
    }//GEN-LAST:event_btnClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel lblScore;
    private javax.swing.JLabel lblTurn;
    // End of variables declaration//GEN-END:variables
}
